SELECT FIRST_HALF.FLAVOR 
from FIRST_HALF
left join ICECREAM_INFO on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
where ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based' and FIRST_HALF.TOTAL_ORDER >'3000'
order by FIRST_HALF.TOTAL_ORDER desc
