SELECT PRODUCT_CODE, sum(PRODUCT.PRICE * OFFLINE_SALE.SALES_AMOUNT) as SALES
from PRODUCT
left join OFFLINE_SALE on PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID 
GROUP by PRODUCT_CODE
order by SALES desc, PRODUCT.PRODUCT_CODE asc